apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: multipathd-start
spec:
  matchSelector: {}
  filename: 99_multipathd.yaml
  contents: |
    stages:
      network:
      - name: "Configure multipathd"
        files:
        - path: /etc/multipath.conf
          content: |
            defaults {
                user_friendly_names yes
                find_multipaths yes
            }

            blacklist {
            }

            devices {
                device {
                    vendor "(HITACHI|HP)"
                    product "OPEN-.*"
                    path_grouping_policy "multibus"
                    path_checker "tur"
                    features "0"
                    failback immediate
                    hardware_handler "0"
                    prio "const"
                    rr_weight uniform
                    no_path_retry 10
                }
            }
          permissions: 0644
      - name: "Start multipathd service"
        systemctl:
          enable:
          - multipathd
          start:
          - multipathd
