kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: demo-storageclass
provisioner: block.csi.ibm.com
parameters:
  pool: demo-pool
  io_group: demo-iogrp             # Optional.
  volume_group: demo-volumegroup   # Optional.
  SpaceEfficiency: thin            # Optional. Do not set this optional parameter if virt_snap_func is set to "true"
  volume_name_prefix: demo-prefix  # Optional.
  virt_snap_func: "false"          # Optional. Values "true"/"false". The default is "false". If set, this value MUST be identical to the value set in the VolumeSnapshotClass yamls

  csi.storage.k8s.io/fstype: xfs   # Optional. Values ext4/xfs. The default is ext4.
  csi.storage.k8s.io/secret-name: demo-secret
  csi.storage.k8s.io/secret-namespace: default
allowVolumeExpansion: true
